/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.MotionController
{
    public class InitMotorsRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "motion_controller/InitMotors";

        //  Sets all motors to zero power for 500 milliseconds, which initializes the motor
        //  controllers.
        //  NOTE: the reason we have to do this is that the motor controllers are made for
        //  remote control planes, and want the plane's controller to zero the joystick 
        //  before flight.

        public InitMotorsRequest()
        {
        }
    }
}
