/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.MotionController
{
    public class SetDepthRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "motion_controller/SetDepth";

        //  Desired depth in meters
        public float depth;

        public SetDepthRequest()
        {
            this.depth = 0.0f;
        }

        public SetDepthRequest(float depth)
        {
            this.depth = depth;
        }
    }
}
