/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.MotionController
{
    public class SetEnabledRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "motion_controller/SetEnabled";

        //  Sets whether PID control is enabled
        public bool enabled;

        public SetEnabledRequest()
        {
            this.enabled = false;
        }

        public SetEnabledRequest(bool enabled)
        {
            this.enabled = enabled;
        }
    }
}
