/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.MotionController
{
    public class SetForwardsPowerRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "motion_controller/SetForwardsPower";

        //  Forwards power, as a percentage from -1.0-1.0
        //  Negative values will make the sub drive backwards.
        public float forwardsPower;

        public SetForwardsPowerRequest()
        {
            this.forwardsPower = 0.0f;
        }

        public SetForwardsPowerRequest(float forwardsPower)
        {
            this.forwardsPower = forwardsPower;
        }
    }
}
