/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.MotionController
{
    public class SetRollPitchAnglesRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "motion_controller/SetRollPitchAngles";

        //  Roll and pitch angles in degrees.  0 degrees on both sets the robot straight up.  Positive angles rotate counterclockwise
        public float roll;
        public float pitch;

        public SetRollPitchAnglesRequest()
        {
            this.roll = 0.0f;
            this.pitch = 0.0f;
        }

        public SetRollPitchAnglesRequest(float roll, float pitch)
        {
            this.roll = roll;
            this.pitch = pitch;
        }
    }
}
