/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.MotionController
{
    public class SetYawAngleRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "motion_controller/SetYawAngle";

        //  Set the yaw angle of the sub. 0 yaw is straight ahead compared to where the sub was
        //  pointing when the IMU was last reset
        public float yaw;

        public SetYawAngleRequest()
        {
            this.yaw = 0.0f;
        }

        public SetYawAngleRequest(float yaw)
        {
            this.yaw = yaw;
        }
    }
}
