/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.MotionController
{
    public class ZeroRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "motion_controller/Zero";

        //  Zeros the PID controller: sets all control targets to the current sensor values

        public ZeroRequest()
        {
        }
    }
}
